//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitObservation) DeepCopyInto(out *ContainerResourceLimitObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitObservation.
func (in *ContainerResourceLimitObservation) DeepCopy() *ContainerResourceLimitObservation {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitParameters) DeepCopyInto(out *ContainerResourceLimitParameters) {
	*out = *in
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitParameters.
func (in *ContainerResourceLimitParameters) DeepCopy() *ContainerResourceLimitParameters {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitObservation) DeepCopyInto(out *LimitObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitObservation.
func (in *LimitObservation) DeepCopy() *LimitObservation {
	if in == nil {
		return nil
	}
	out := new(LimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitParameters) DeepCopyInto(out *LimitParameters) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitParameters.
func (in *LimitParameters) DeepCopy() *LimitParameters {
	if in == nil {
		return nil
	}
	out := new(LimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RancherNamespace) DeepCopyInto(out *RancherNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RancherNamespace.
func (in *RancherNamespace) DeepCopy() *RancherNamespace {
	if in == nil {
		return nil
	}
	out := new(RancherNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RancherNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RancherNamespaceList) DeepCopyInto(out *RancherNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RancherNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RancherNamespaceList.
func (in *RancherNamespaceList) DeepCopy() *RancherNamespaceList {
	if in == nil {
		return nil
	}
	out := new(RancherNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RancherNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RancherNamespaceObservation) DeepCopyInto(out *RancherNamespaceObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RancherNamespaceObservation.
func (in *RancherNamespaceObservation) DeepCopy() *RancherNamespaceObservation {
	if in == nil {
		return nil
	}
	out := new(RancherNamespaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RancherNamespaceParameters) DeepCopyInto(out *RancherNamespaceParameters) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ContainerResourceLimit != nil {
		in, out := &in.ContainerResourceLimit, &out.ContainerResourceLimit
		*out = make([]ContainerResourceLimitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = make([]ResourceQuotaParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitForCluster != nil {
		in, out := &in.WaitForCluster, &out.WaitForCluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RancherNamespaceParameters.
func (in *RancherNamespaceParameters) DeepCopy() *RancherNamespaceParameters {
	if in == nil {
		return nil
	}
	out := new(RancherNamespaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RancherNamespaceSpec) DeepCopyInto(out *RancherNamespaceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RancherNamespaceSpec.
func (in *RancherNamespaceSpec) DeepCopy() *RancherNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(RancherNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RancherNamespaceStatus) DeepCopyInto(out *RancherNamespaceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RancherNamespaceStatus.
func (in *RancherNamespaceStatus) DeepCopy() *RancherNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(RancherNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaObservation) DeepCopyInto(out *ResourceQuotaObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaObservation.
func (in *ResourceQuotaObservation) DeepCopy() *ResourceQuotaObservation {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaParameters) DeepCopyInto(out *ResourceQuotaParameters) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = make([]LimitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaParameters.
func (in *ResourceQuotaParameters) DeepCopy() *ResourceQuotaParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaParameters)
	in.DeepCopyInto(out)
	return out
}
